services:
  web:
    build:
      context: ./Server
      dockerfile: Dockerfile
    container_name: flask_app
    networks:
      - flask-monitor
    ports:
      - "5000:5000"
    env_file:
      - ./Server/.env.docker
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6.0
    container_name: mongo_db
    restart: always
    env_file:
      - .env.mongo
    volumes:
      - mongo_data:/data/db
    networks:
      - flask-monitor

volumes:
  mongo_data:

networks:
  flask-monitor:
