apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
  namespace: google-classroom-application
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
