apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: google-classroom-application
spec:
  serviceName: mongodb-svc
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongo
          image: mongo:6.0
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: google-classroom-configuration
                  key: MONGODB_ROOT_USERNAME

            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: google-classroom-secret
                  key: MONGODB_ROOT_PASSWORD

            - name: MONGO_INITDB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: google-classroom-configuration
                  key: MONGODB_INIT_DB
          volumeMounts:
            - name: mongodb-storage
              mountPath: /data/db
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: mongodb-storage
          persistentVolumeClaim:
            claimName: mongodb-pvc

