apiVersion: v1
kind: Service
metadata:
  name: google-classroom-server-svc
  namespace: google-classroom-application
spec:
  selector: 
    app: google-classroom-server
  ports:
    - name: server
      port: 5000
      targetPort: 5000
  type: ClusterIP

